//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarPoolingTecWebApi22019.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBJETOS_INTERCAMBIO
    {
        public int OI_ID { get; set; }
        public int OI_userID { get; set; }
        public string OI_nombre { get; set; }
        public int OI_cantidad { get; set; }
        public int OI_puntaje { get; set; }
        public int OI_precio { get; set; }
        public string OI_fecha { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
    }
}
