//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarPoolingTecWebApi22019.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TELEFONO
    {
        public string TE_telefono { get; set; }
        public int TE_userID { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
    }
}
