//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarPoolingTecWebApi22019.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIAJESXUSUARIO
    {
        public int VU_codigoViaje { get; set; }
        public int VU_viajeID { get; set; }
        public int VU_userID { get; set; }
        public Nullable<int> VU_puntajeXviaje { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
        public virtual VIAJE VIAJE { get; set; }
    }
}
